# -*- coding: utf-8 -*-
"""Random Forest IDS Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ijx2M7NO81psQBZj2Kph5qUVPtG2JEQm

## **Step 1 : Environment Setup & Library Imports**
"""

import pandas as pd
from sklearn import tree
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_text
import matplotlib.pyplot as plt
from json import loads, dumps
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    roc_curve,
    auc
)
import seaborn as sns
from io import StringIO
from json import loads, dumps

"""## **Step 2 : Load the IoTID20 Dataset**"""

df = pd.DataFrame(pd.read_csv("IoT Network Intrusion Dataset.csv"))

print(f"   Total Samples  : {df.shape[0]:,}")
print(f"   Total Features : {df.shape[1] - 1}")

#Visual Dataset Attacks
Df_Attack=df['Cat']

fig, axes = plt.subplots(2, figsize=(14, 5))
Df_Attack.value_counts().head(10).plot(
kind='barh', ax=axes[0])
axes[0].set_title('Top Attack Categories')
plt.tight_layout()
plt.show()

"""## **Step 3 : Define Features and Exploratory Data Analysis**"""

Df_Attack=df['Cat']
Df_ACK_Flag_Cnt=df['ACK_Flag_Cnt']
Df_SYN_FLag_Cnt=df['SYN_Flag_Cnt']
Df_Dst_Port=df['Dst_Port']
Df_Src_Port=df['Src_Port']
Df_Protocol=df['Protocol']
Df_Pkt_Size_Avg=df['Pkt_Size_Avg']
Df_Flow_Duration=df['Flow_Duration']

print("Missing values per column:")
print(df.isnull().sum().sum())

"""## **Step 4 : Build , Train and Evaluation  Decision Tree**

### **Decision Tree 1**
"""

def Decision_Tree_1():
  #Train Dataset IoTID20 for Decision Tree 1
  x = df[['ACK_Flag_Cnt','SYN_Flag_Cnt','Dst_Port','Src_Port','Protocol','Pkt_Size_Avg']]
  y = df[['Cat']]

  x_train,x_test,y_train,y_test = train_test_split (x,y, test_size = 0.45, random_state = 25)
  decision_tree = DecisionTreeClassifier( random_state=20,max_depth=6)
  decision_tree = decision_tree.fit(x_train,y_train)
  print(f"\\n🔀 Train/Test Split:")
  print(f"   Training samples : {x_train.shape[0]:,}")
  print(f"   Testing samples  : {x_test.shape[0]:,}")
  Decision_Tree_1_Report = export_text(decision_tree,feature_names=['ACK_Flag_Cnt','SYN_Flag_Cnt','Dst_Port','Src_Port','Protocol','Pkt_Size_Avg'])
  print(Decision_Tree_1_Report)

  conditions=[

            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol <= 11.5) & (Df_Src_Port<= 261.5)&(Df_Dst_Port<= 36955 )&(Df_Pkt_Size_Avg<= 97.25),#4
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol <= 11.5) & (Df_Src_Port<= 261.5)&(Df_Dst_Port<= 36955 )&(Df_Pkt_Size_Avg> 97.25),#4
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol <= 11.5) & (Df_Src_Port<= 261.5)&(Df_Dst_Port> 36955 )&(Df_Dst_Port<= 51760 ),#3
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol <= 11.5) & (Df_Src_Port<= 261.5)&(Df_Dst_Port> 51760 ),#1
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol <= 11.5)&(Df_Src_Port<= 9004) & (Df_Src_Port> 261.5)&(Df_Dst_Port<= 43189.5 ),#3
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol <= 11.5)&(Df_Src_Port> 261.5) & (Df_Src_Port<= 9004)&(Df_Dst_Port> 43189.5 )&(Df_Dst_Port<= 52591 ),#3
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol <= 11.5)&(Df_Src_Port> 261.5) & (Df_Src_Port<= 9004)&(Df_Dst_Port <= 55838 )&(Df_Dst_Port > 52591 ),#5

            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol <= 11.5)&(Df_Src_Port> 261.5) & (Df_Src_Port<= 9004)&(Df_Dst_Port > 55838 ),#3
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol <= 11.5)&(Df_Src_Port<= 9310) & (Df_Src_Port> 9004)&(Df_Dst_Port <= 47064 ),#2
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol <= 11.5)&(Df_Src_Port<= 9310) & (Df_Src_Port> 9004)&(Df_Dst_Port > 47064 )&(Df_Dst_Port <= 51251 ),#1
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol <= 11.5)&(Df_Src_Port<= 9310) & (Df_Src_Port> 9004)&(Df_Dst_Port > 51251 )&(Df_Dst_Port <= 52829 ),#5
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol <= 11.5)&(Df_Src_Port<= 9310) & (Df_Src_Port> 9004)&(Df_Dst_Port > 52829 ),#3
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol <= 11.5)&(Df_Src_Port> 9310) & (Df_Src_Port<= 52703),#3
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol <= 11.5)&(Df_Src_Port<= 52739) & (Df_Src_Port> 52703),#5

            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol <= 11.5)&(Df_Src_Port<= 53575) & (Df_Src_Port> 52739),#4
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol <= 11.5)&(Df_Src_Port> 53575),#3
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol > 11.5) & (Df_Src_Port<= 1171)&(Df_Dst_Port<= 14436.50 )&(Df_Pkt_Size_Avg<= 1380.925),#2
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol > 11.5) & (Df_Src_Port<= 1171)&(Df_Dst_Port> 14436.50 )&(Df_Dst_Port<= 50165)&(Df_Pkt_Size_Avg<= 1380.92),#3
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol > 11.5) & (Df_Src_Port<= 1171)&(Df_Dst_Port > 50165 )&(Df_Dst_Port<= 64433 )&(Df_Pkt_Size_Avg<= 1380.92),#4
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol > 11.5) & (Df_Src_Port<= 1171)&(Df_Dst_Port > 64433 )&(Df_Pkt_Size_Avg<= 1380.92),#2
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol > 11.5) & (Df_Src_Port<= 1171)&(Df_Dst_Port<= 50169 )&(Df_Pkt_Size_Avg> 1380.92),#3

            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol > 11.5) & (Df_Src_Port<= 1171)&(Df_Dst_Port> 50169 )&(Df_Dst_Port<= 58167.5 )&(Df_Pkt_Size_Avg> 1380.92),#5
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol > 11.5) & (Df_Src_Port<= 1171)&(Df_Dst_Port> 58167.5 )&(Df_Pkt_Size_Avg> 1380.92),#3
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol > 11.5) & (Df_Src_Port> 1171)&(Df_Src_Port<= 40248)&(Df_Dst_Port<= 976.5 ),#2
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol > 11.5) & (Df_Src_Port> 1171)&(Df_Src_Port<= 40248)&(Df_Dst_Port>976.5 )&(Df_Dst_Port<=6001 ),#3
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol > 11.5) & (Df_Src_Port<= 44786.5)&(Df_Src_Port> 40248)&(Df_Dst_Port<=6001 ),#4
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol > 11.5) & (Df_Src_Port> 44786.5)&(Df_Dst_Port<=6001 ),#3
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol > 11.5) & (Df_Src_Port> 1171)& (Df_Src_Port<= 10104)&(Df_Dst_Port>6001 ),#3


            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol > 11.5) & (Df_Src_Port<= 48878.5)& (Df_Src_Port> 10104)&(Df_Dst_Port>6001 ),#2
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol > 11.5) & (Df_Src_Port >48878.5 )&(Df_Dst_Port<=30179.5 )&(Df_Dst_Port>6001 ),#3
            (Df_SYN_FLag_Cnt<= 0.5 ) & (Df_Protocol > 11.5) & (Df_Src_Port >48878.5 )&(Df_Dst_Port>30179.5 ),#5
            (Df_SYN_FLag_Cnt> 0.5 )  & (Df_Src_Port <= 26528)&(Df_Dst_Port<= 498.5 )&(Df_Pkt_Size_Avg <= 4),#3
             (Df_SYN_FLag_Cnt> 0.5 )  & (Df_Src_Port <= 46821.5)&(Df_Src_Port > 26528)&(Df_Dst_Port<= 498.5 )&(Df_Pkt_Size_Avg <= 4),#5
            (Df_SYN_FLag_Cnt> 0.5 )  & (Df_Src_Port > 46821.5)&(Df_Dst_Port<= 498.5 )&(Df_Pkt_Size_Avg <= 4),#3
            (Df_SYN_FLag_Cnt> 0.5 ) &(Df_Dst_Port<= 498.5 )&(Df_Pkt_Size_Avg > 4)&(Df_ACK_Flag_Cnt<= 0.5),#2

            (Df_SYN_FLag_Cnt> 0.5 ) &(Df_Dst_Port<= 498.5 )& (Df_Src_Port <= 54764)&(Df_Pkt_Size_Avg > 4)&(Df_ACK_Flag_Cnt> 0.5),#3
            (Df_SYN_FLag_Cnt> 0.5 ) &(Df_Dst_Port<= 498.5 )& (Df_Src_Port > 54764)&(Df_Pkt_Size_Avg <= 40.17)&(Df_ACK_Flag_Cnt> 0.5),#4
            (Df_SYN_FLag_Cnt> 0.5 ) &(Df_Dst_Port<= 498.5 )& (Df_Src_Port > 54764)&(Df_Pkt_Size_Avg > 40.17)&(Df_ACK_Flag_Cnt> 0.5),#2
            (Df_SYN_FLag_Cnt> 0.5 )  & (Df_Src_Port <= 498.5)&(Df_Dst_Port> 498.5 )&(Df_Pkt_Size_Avg <= 1370.43),#2
           (Df_SYN_FLag_Cnt> 0.5 )  & (Df_Src_Port > 498.5)& (Df_Src_Port <= 9010)&(Df_Dst_Port> 498.5 )&(Df_Pkt_Size_Avg <= 1370.43),#2
            (Df_SYN_FLag_Cnt> 0.5 )  & (Df_Src_Port <= 34523)&(Df_Src_Port> 9010 )&(Df_Dst_Port> 498.5 )&(Df_Pkt_Size_Avg <= 1370.43),#5
            (Df_SYN_FLag_Cnt> 0.5 )  & (Df_Src_Port > 34523)& (Df_Src_Port <= 46344.5)&(Df_Dst_Port> 498.5 )&(Df_Pkt_Size_Avg <= 1370.43),#2

            (Df_SYN_FLag_Cnt> 0.5 )  & (Df_Src_Port <= 4731.50)&(Df_Dst_Port> 498.5 )&(Df_Pkt_Size_Avg > 1370.43),#3
             (Df_SYN_FLag_Cnt> 0.5 )  & (Df_Src_Port > 4731.50)& (Df_Src_Port <= 46344.5)&(Df_Dst_Port> 498.5 )&(Df_Pkt_Size_Avg > 1370.43),#1
            (Df_SYN_FLag_Cnt> 0.5 )  & (Df_Src_Port <= 50047.5)& (Df_Src_Port > 46344.5)&(Df_Dst_Port> 498.5 ),#1
            (Df_SYN_FLag_Cnt> 0.5 )  & (Df_Src_Port <= 51020)& (Df_Src_Port > 50047.5)&(Df_Dst_Port> 498.5 ),#4
            (Df_SYN_FLag_Cnt> 0.5 )  & (Df_Src_Port > 51020)& (Df_Src_Port <= 54471.50)&(Df_Dst_Port> 498.5 ),#5
            (Df_SYN_FLag_Cnt> 0.5 )  & (Df_Src_Port > 54471.5)& (Df_Src_Port <= 58311.5)&(Df_Dst_Port> 498.5 ),#3
            (Df_SYN_FLag_Cnt> 0.5 )  & (Df_Src_Port > 58311.5)&(Df_Dst_Port> 498.5 ),#2

        ]

  Type_attack=["MITM ARP Spoofing","MITM ARP Spoofing","Mirai","Normal","Mirai","Mirai","Scan",
                 "Mirai","DoS","Normal","Scan","Mirai","Mirai","Scan",
                 "MITM ARP Spoofing","Mirai","DoS","Mirai","MITM ARP Spoofing","DoS","Mirai",
                 "Scan","Mirai","DoS","Mirai","MITM ARP Spoofing","Mirai","Mirai",
                 "DoS","Mirai","Scan","Mirai","Scan","Mirai","DoS",
                 "Mirai","MITM ARP Spoofing","DoS","DoS","DoS","Scan","DoS",
                 "Mirai","Normal","Normal","MITM ARP Spoofing","Scan","Mirai","DoS"]


  result=np.select(conditions,Type_attack,"Normal")
  df_result=pd.DataFrame(result,columns=['Result'])
  df_result.to_csv("Result_Decision_Tree1.csv", index=None, header=True)

  y_true = df['Cat']
  y_pred = df_result['Result']
  target_names = ['MITM ARP Spoofing','Normal','DoS', 'Mirai','Scan']

  print(classification_report(y_true, y_pred, target_names=target_names,digits=4))

  cm = confusion_matrix(y_true, y_pred)
  fig, ax = plt.subplots(figsize=(5, 6))
  sns.heatmap(cm, annot=True, fmt=',', cmap='Blues',xticklabels=target_names,yticklabels=target_names, ax=ax)
  ax.set_xlabel('Predicted Label')
  ax.set_ylabel('True Label')
  ax.set_title('Confusion Matrix — Decision Tree IDS')
  plt.tight_layout()
  plt.show()





Decision_Tree_1()

"""### **Decision Tree 2**"""

def Decision_Tree_2():
  #Train Dataset IoTID20 for Decision Tree 2
  x = df[['Dst_Port','Src_Port','Flow_Duration','Pkt_Size_Avg']]
  y = df[['Cat']]

  x_train,x_test,y_train,y_test = train_test_split (x,y, test_size = 0.3, random_state = 10)
  decision_tree = DecisionTreeClassifier( random_state=10,max_depth=6)
  decision_tree = decision_tree.fit(x_train,y_train)
  print(f"\\n🔀 Train/Test Split:")
  print(f"   Training samples : {x_train.shape[0]:,}")
  print(f"   Testing samples  : {x_test.shape[0]:,}")
  Decision_Tree_1_Report = export_text(decision_tree,feature_names=['Dst_Port','Src_Port','Flow_Duration','Pkt_Size_Avg'])
  print(Decision_Tree_1_Report)


  conditions=[

            (Df_Flow_Duration<= 185 ) & (Df_Src_Port<= 66.5)&(Df_Dst_Port<= 52663 ),#4
            (Df_Flow_Duration > 185 ) & (Df_Flow_Duration<= 300.5 )& (Df_Src_Port<= 66.5)&(Df_Dst_Port<= 52663 ),#3
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port> 66.5)&(Df_Src_Port <= 52418.50)&(Df_Dst_Port<= 49722 ),#3
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port> 66.5)&(Df_Src_Port <= 52418.50)&(Df_Dst_Port> 49722 )& (Df_Dst_Port<= 52663 ),#3
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port<= 9015)&(Df_Dst_Port> 52663 )&(Df_Dst_Port<= 52907.50 ),#5
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port<= 52418.50)&(Df_Src_Port> 9015)&(Df_Dst_Port> 52663 )&(Df_Dst_Port<= 52907.50 ),#5
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port<= 5614)&(Df_Dst_Port> 52907.50 ),#3

            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port> 5614)&(Df_Src_Port<= 52418.50)&(Df_Dst_Port> 52907.50 ),#3
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port> 52418.50)&(Df_Src_Port<= 52703.50),#5
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port >52703.50 )&(Df_Src_Port<= 52734.50),#5
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port <= 52738.50 )&(Df_Src_Port> 52734.50),#3
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port <= 52739.50 )&(Df_Src_Port> 52738.50),#5
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port <= 52788 )&(Df_Src_Port> 52739.50),#4
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port <= 53179 )&(Df_Src_Port> 52788),#3

            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port <= 53589.50 )&(Df_Src_Port> 53179)&(Df_Dst_Port<= 1171.5),#4
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port <= 53589.50 )&(Df_Src_Port> 53179)&(Df_Dst_Port> 1171.5),#4
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port <= 56250 )&(Df_Src_Port> 53589.50)&(Df_Dst_Port<= 7050)&(Df_Pkt_Size_Avg<= 2181),#3
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port <= 56898.5 )&(Df_Src_Port>56250 )&(Df_Dst_Port<= 7050)&(Df_Pkt_Size_Avg<= 2181),#3
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port <= 56216.5 )&(Df_Src_Port>53589.50 )&(Df_Dst_Port<= 7050)&(Df_Pkt_Size_Avg> 2181),#3
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port <= 56898.50 )&(Df_Src_Port> 56216.5 )&(Df_Dst_Port<= 7050),#4
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port > 56898.50 )&(Df_Src_Port<= 57694.50 )&(Df_Dst_Port<= 7050),#3

            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port > 57694.50 )&(Df_Src_Port<= 58047 )&(Df_Dst_Port<= 7050),#4
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port > 58047 )&(Df_Src_Port<= 60912.50 )&(Df_Dst_Port<= 7050),#3
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port> 60912.50 )&(Df_Dst_Port<= 7050),#4
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port > 53589.50 )&(Df_Src_Port<= 57740.5 )&(Df_Dst_Port> 7050)&(Df_Pkt_Size_Avg<= 19.29),#3
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port> 57740.5 )&(Df_Dst_Port> 7050)&(Df_Pkt_Size_Avg<= 19.29),#4
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port<= 54470 )&(Df_Src_Port> 53589.50 )&(Df_Dst_Port> 7050)&(Df_Pkt_Size_Avg> 19.29)&(Df_Pkt_Size_Avg<= 2181),#5
            (Df_Flow_Duration<= 300.5 )&(Df_Src_Port> 57740.5 )&(Df_Dst_Port> 7050)&(Df_Pkt_Size_Avg> 19.29)&(Df_Pkt_Size_Avg<= 2181),#3

            (Df_Flow_Duration<= 161.5 )&(Df_Src_Port> 53589.50 )&(Df_Dst_Port> 7050)&(Df_Pkt_Size_Avg> 2181),#4
            (Df_Flow_Duration> 161.5 )&(Df_Flow_Duration<= 300.5 )&(Df_Src_Port> 53589.50 )&(Df_Dst_Port> 7050)&(Df_Pkt_Size_Avg> 2181),#1
            (Df_Flow_Duration> 300.5 )&(Df_Flow_Duration<= 550.5 )&(Df_Src_Port <= 261.5 )&(Df_Pkt_Size_Avg<= 5),#1
            (Df_Flow_Duration> 300.5 )&(Df_Flow_Duration<= 550.5 )&(Df_Src_Port > 261.5 )&(Df_Src_Port <= 750 )&(Df_Pkt_Size_Avg<= 5),#1
            (Df_Flow_Duration> 300.5 )&(Df_Flow_Duration<= 550.5 )&(Df_Src_Port <=9009 )&(Df_Src_Port > 750 )&(Df_Dst_Port<= 33398)&(Df_Pkt_Size_Avg<= 5),#2
            (Df_Flow_Duration> 300.5 )&(Df_Flow_Duration<= 550.5 )&(Df_Src_Port <=9009 )&(Df_Src_Port > 750 )&(Df_Dst_Port> 33398)&(Df_Pkt_Size_Avg<= 5),#1
            (Df_Flow_Duration<= 311.5 )&(Df_Flow_Duration> 300.5 )&(Df_Src_Port <=9009 )&(Df_Dst_Port<= 54738)&(Df_Pkt_Size_Avg> 5),#1

            (Df_Flow_Duration> 311.5 )&(Df_Flow_Duration<= 550.5 )&(Df_Src_Port <=9009 )&(Df_Dst_Port<= 54738)&(Df_Pkt_Size_Avg> 5),#1
            (Df_Flow_Duration<= 550.5 )&(Df_Src_Port <=9009 )&(Df_Dst_Port<= 55328)&(Df_Dst_Port> 54738)&(Df_Pkt_Size_Avg> 5),#2
            (Df_Flow_Duration<= 550.5 )&(Df_Src_Port <=9009 )&(Df_Dst_Port> 55328)&(Df_Pkt_Size_Avg> 5),#1
            (Df_Flow_Duration<= 550.5 )&(Df_Flow_Duration> 300.5 )&(Df_Src_Port <= 49852.50 )&(Df_Src_Port > 9009 ),#1
            (Df_Flow_Duration<= 550.5 )&(Df_Flow_Duration> 300.5 )&(Df_Src_Port > 49852.50 )&(Df_Src_Port <= 51770.50 )&(Df_Src_Port > 9009 ),#1
            (Df_Flow_Duration<= 550.5 )&(Df_Flow_Duration> 300.5 )&(Df_Src_Port > 51770.50 )&(Df_Src_Port <= 52637 ),#2
            (Df_Flow_Duration<= 550.5 )&(Df_Flow_Duration> 300.5 )&(Df_Src_Port <= 59582.50 )&(Df_Src_Port > 52637 ),#1

            (Df_Flow_Duration<= 550.5 )&(Df_Flow_Duration> 300.5 )&(Df_Src_Port > 59582.5 )&(Df_Dst_Port<= 2899 ),#1
            (Df_Flow_Duration<= 550.5 )&(Df_Flow_Duration> 300.5 )&(Df_Src_Port > 59582.5 )&(Df_Dst_Port> 2899 ),#2
            (Df_Flow_Duration> 550.5 )#2


        ]

  Type_attack=["MITM ARP Spoofing","Mirai","Mirai","Mirai","Scan","Scan","Mirai",
                 "Mirai","Scan","Scan","Mirai","Scan","MITM ARP Spoofing","Mirai",
                 "MITM ARP Spoofing","MITM ARP Spoofing","Mirai","Mirai","Mirai","MITM ARP Spoofing","Mirai",
                 "MITM ARP Spoofing","Mirai","MITM ARP Spoofing","Mirai","MITM ARP Spoofing","Scan","Mirai",
                 "MITM ARP Spoofing","Normal","Normal","Normal","DoS","Normal","Normal",
                 "Normal","DoS","Normal","Normal","Normal","DoS","Normal",
                 "Normal","DoS","DoS"]


  result=np.select(conditions,Type_attack,"Normal")

  df_result=pd.DataFrame(result,columns=['Result'])
  df_result.to_csv("Result_Decision_Tree2.csv", index=None, header=True)

  y_true = df['Cat']
  y_pred = df_result['Result']
  target_names = ['MITM ARP Spoofing','Normal','DoS', 'Mirai','Scan']

  print(classification_report(y_true, y_pred, target_names=target_names))

  cm = confusion_matrix(y_true, y_pred)
  fig, ax = plt.subplots(figsize=(5, 6))
  sns.heatmap(cm, annot=True, fmt=',', cmap='Blues',xticklabels=target_names,yticklabels=target_names, ax=ax)
  ax.set_xlabel('Predicted Label')
  ax.set_ylabel('True Label')
  ax.set_title('Confusion Matrix — Decision Tree IDS')
  plt.tight_layout()
  plt.show()

Decision_Tree_2()

"""### **Decision Tree 3**"""

def Decision_Tree_3():
  #Train Dataset IoTID20 for Decision Tree 3
  x = df[['ACK_Flag_Cnt','SYN_Flag_Cnt','Pkt_Size_Avg','Flow_Duration']]
  y = df[['Cat']]

  x_train,x_test,y_train,y_test = train_test_split (x,y, test_size = 0.2, random_state = 15)
  decision_tree = DecisionTreeClassifier( random_state=20,max_depth=6)
  decision_tree = decision_tree.fit(x_train,y_train)
  print(f"\\n🔀 Train/Test Split:")
  print(f"   Training samples : {x_train.shape[0]:,}")
  print(f"   Testing samples  : {x_test.shape[0]:,}")
  Decision_Tree_1_Report = export_text(decision_tree,feature_names=['ACK_Flag_Cnt','SYN_Flag_Cnt','Pkt_Size_Avg','Flow_Duration'])
  print(Decision_Tree_1_Report)

  conditions=[



            (Df_Flow_Duration<= 65 )&(Df_Pkt_Size_Avg <= 10.12)&(Df_ACK_Flag_Cnt <=0.5) ,#3
            (Df_Flow_Duration >65 )&(Df_Flow_Duration <= 185 )&(Df_SYN_FLag_Cnt <=0.5)&(Df_Pkt_Size_Avg <= 10.12 ) & (Df_ACK_Flag_Cnt <=0.5 ),#4

            (Df_SYN_FLag_Cnt > 0.5)&(Df_Flow_Duration >65 )&(Df_Flow_Duration <= 185)&(Df_Pkt_Size_Avg<=10.12)&( Df_ACK_Flag_Cnt <= 0.5),#5
            (Df_Flow_Duration <=249.5)&(Df_Flow_Duration > 185)&(Df_SYN_FLag_Cnt <= 0.5)& (Df_Pkt_Size_Avg<=10.12)&(Df_ACK_Flag_Cnt<=0.5),#3
            (Df_Flow_Duration >249.5)&(Df_Flow_Duration <=300.5)&(Df_SYN_FLag_Cnt <= 0.5)& (Df_Pkt_Size_Avg<=10.12)&(Df_ACK_Flag_Cnt<=0.5),#3
            (Df_Flow_Duration <=294.5)&(Df_Flow_Duration > 185)&(Df_SYN_FLag_Cnt > 0.5)& (Df_Pkt_Size_Avg<=10.12)&(Df_ACK_Flag_Cnt<=0.5),#2
            (Df_Flow_Duration >294.5)&(Df_Flow_Duration <=300.5)&(Df_SYN_FLag_Cnt > 0.5)& (Df_Pkt_Size_Avg<=10.12)&(Df_ACK_Flag_Cnt<=0.5),#3
            (Df_Flow_Duration <=71.5)&(Df_Pkt_Size_Avg <= 114.25)&(Df_Pkt_Size_Avg > 10.12)&(Df_ACK_Flag_Cnt<=0.5),#3
            (Df_Pkt_Size_Avg<=46.45)&(Df_Flow_Duration >71.5)&(Df_Flow_Duration <= 300.5)&(Df_ACK_Flag_Cnt<=0.5),#3

            (Df_Pkt_Size_Avg>46.45)&(Df_Pkt_Size_Avg<=46.45)&(Df_Flow_Duration <=300.5)&(Df_ACK_Flag_Cnt <= 0.5),#3
            (Df_Pkt_Size_Avg<=542.33)&(Df_Pkt_Size_Avg>114.25)&(Df_Flow_Duration <=300.5)&(Df_ACK_Flag_Cnt <= 0.5),#3
            (Df_Pkt_Size_Avg>542.33)&(Df_Pkt_Size_Avg<= 682.75)&(Df_Flow_Duration <=300.5)&(Df_ACK_Flag_Cnt <= 0.5),#3
            (Df_Pkt_Size_Avg>682.75) &(Df_Flow_Duration <=177.5)&(Df_ACK_Flag_Cnt <= 0.5),#3
            (Df_Pkt_Size_Avg> 682.75)&(Df_Flow_Duration > 177.5)&(Df_Flow_Duration <= 300.5)&(Df_ACK_Flag_Cnt <= 0.5),#3
            (Df_Pkt_Size_Avg<=1851.75)&(Df_Flow_Duration <=180.5)&(Df_ACK_Flag_Cnt > 0.5),#3
            (Df_Pkt_Size_Avg>1851.75)& (Df_Pkt_Size_Avg<=2082.25)&(Df_Flow_Duration <=180.5)&(Df_ACK_Flag_Cnt > 0.5),#3

            (Df_Pkt_Size_Avg>2081.5)&(Df_Pkt_Size_Avg<=2082.25)&(Df_Flow_Duration <=163.5)&(Df_ACK_Flag_Cnt > 0.5),#5
            (Df_Pkt_Size_Avg>2081.5)&(Df_Pkt_Size_Avg<=2082.25)&(Df_Flow_Duration >163.5)&(Df_Flow_Duration <=180.5)&(Df_ACK_Flag_Cnt > 0.5),#1
            (Df_Pkt_Size_Avg<=1851.75)&(Df_Flow_Duration >180.5)&(Df_Flow_Duration <=300.5)&(Df_ACK_Flag_Cnt > 0.5),#3
            (Df_Pkt_Size_Avg>1851.75)&(Df_Pkt_Size_Avg<=2065.25)&(Df_Flow_Duration >180.5)&(Df_Flow_Duration <=300.5)&(Df_ACK_Flag_Cnt > 0.5),#3
            (Df_Pkt_Size_Avg>2065.25)&(Df_Pkt_Size_Avg>2082.25)&(Df_Flow_Duration >180.5)&(Df_Flow_Duration <=273.5)&(Df_ACK_Flag_Cnt > 0.5),#1
            (Df_Pkt_Size_Avg>2065.25)&(Df_Pkt_Size_Avg>2082.25)&(Df_Flow_Duration <=300.5)&(Df_Flow_Duration >273.5)&(Df_ACK_Flag_Cnt > 0.5),#1
            (Df_Pkt_Size_Avg<=2102.25)&(Df_Pkt_Size_Avg>2082.25)&(Df_Flow_Duration <=300.5)&(Df_ACK_Flag_Cnt > 0.5),#3

            (Df_Pkt_Size_Avg<=2127.5)&(Df_Pkt_Size_Avg>2102.25)&(Df_Flow_Duration <=300.5)&(Df_ACK_Flag_Cnt > 0.5),#3
            (Df_Pkt_Size_Avg>2127.5)&(Df_Pkt_Size_Avg<=2160.75)&(Df_Flow_Duration <=300.5)&(Df_ACK_Flag_Cnt > 0.5),#3
            (Df_Pkt_Size_Avg<=2161.75)&(Df_Pkt_Size_Avg>2160.75)&(Df_Flow_Duration <=300.5)&(Df_ACK_Flag_Cnt > 0.5),#3
            (Df_Pkt_Size_Avg<=2179)&(Df_Pkt_Size_Avg>2161.75)&(Df_Flow_Duration <=180.5)&(Df_ACK_Flag_Cnt > 0.5),#3
            (Df_Pkt_Size_Avg>2179)&(Df_Flow_Duration <=180.5)&(Df_ACK_Flag_Cnt > 0.5),#3
            (Df_Pkt_Size_Avg<=2181)&(Df_Pkt_Size_Avg>2161.75)&(Df_Flow_Duration <=300.5)&(Df_Flow_Duration >180.5)&(Df_ACK_Flag_Cnt > 0.5),#3
            (Df_Pkt_Size_Avg>2181)&(Df_Pkt_Size_Avg>2161.75)&(Df_Flow_Duration <=300.5)&(Df_Flow_Duration >180.5)&(Df_ACK_Flag_Cnt > 0.5),#3

            (Df_Pkt_Size_Avg<=51)&(Df_Flow_Duration <=385)&(Df_Flow_Duration>300.5)&(Df_ACK_Flag_Cnt <= 0.5)&(Df_SYN_FLag_Cnt<=0.5),#1
            (Df_Pkt_Size_Avg<=51)&(Df_Flow_Duration <=550.5)&(Df_Flow_Duration>385)&(Df_ACK_Flag_Cnt <= 0.5)&(Df_SYN_FLag_Cnt<=0.5),#2
            (Df_Pkt_Size_Avg>51)&(Df_Flow_Duration <=315)&(Df_Flow_Duration>300.5)&(Df_ACK_Flag_Cnt <= 0.5)&(Df_SYN_FLag_Cnt<=0.5),#2
            (Df_Pkt_Size_Avg>51)&(Df_Flow_Duration >315)&(Df_Flow_Duration<=550.5)&(Df_ACK_Flag_Cnt <= 0.5)&(Df_SYN_FLag_Cnt<=0.5),#1
            (Df_Pkt_Size_Avg<=36.83)&(Df_Flow_Duration <=550.5)&(Df_Flow_Duration>300.5)&(Df_ACK_Flag_Cnt <= 0.5)&(Df_SYN_FLag_Cnt<=0.5),#1
            (Df_Pkt_Size_Avg>36.83)&(Df_Pkt_Size_Avg<=37.17)&(Df_Flow_Duration <=550.5)&(Df_Flow_Duration>300.5)&(Df_ACK_Flag_Cnt <= 0.5)&(Df_SYN_FLag_Cnt<=0.5),#2
            (Df_Pkt_Size_Avg<=1023.50)&(Df_Pkt_Size_Avg>37.17)&(Df_Flow_Duration <=550.5)&(Df_Flow_Duration>300.5)&(Df_ACK_Flag_Cnt <= 0.5)&(Df_SYN_FLag_Cnt<=0.5),#1

            (Df_Pkt_Size_Avg>1023.50)&(Df_Flow_Duration <=550.5)&(Df_Flow_Duration>300.5)&(Df_ACK_Flag_Cnt <= 0.5)&(Df_SYN_FLag_Cnt<=0.5),#1
            (Df_Flow_Duration<=436.5)&(Df_Flow_Duration>300.5)&(Df_ACK_Flag_Cnt <= 0.5)&(Df_SYN_FLag_Cnt>0.5),#2
            (Df_Flow_Duration>436.5)&(Df_Flow_Duration<=438)&(Df_ACK_Flag_Cnt <= 0.5)&(Df_SYN_FLag_Cnt>0.5),#2
            (Df_Flow_Duration<=512.5)&(Df_Flow_Duration>438)&(Df_ACK_Flag_Cnt <= 0.5)&(Df_SYN_FLag_Cnt>0.5),#2
            (Df_Flow_Duration>512.5)&(Df_Flow_Duration<=550.5)&(Df_ACK_Flag_Cnt <= 0.5)&(Df_SYN_FLag_Cnt>0.5),#2
            (Df_Flow_Duration>300.5)&(Df_Flow_Duration<=550.5)&(Df_ACK_Flag_Cnt > 0.5)&(Df_SYN_FLag_Cnt>0.5),#1
            (Df_Flow_Duration>550.5)#2

        ]

  Type_attack=["Mirai","MITM ARP Spoofing",
                 "Scan","Mirai","Mirai","DoS","Mirai","Mirai","Mirai",
                "Mirai","Mirai","Mirai","Mirai","Mirai","Mirai","Mirai",
                "Scan","Normal","Mirai","Mirai","Normal","Normal","Mirai",
                "Mirai","Mirai","Mirai","Mirai","Mirai","Mirai","Mirai",
                "Normal","DoS","DoS","Normal","Normal","DoS","Normal",
                "Normal","DoS","DoS","DoS","DoS","Normal","DoS"

                 ]

  result=np.select(conditions,Type_attack,"Normal")


  df_result=pd.DataFrame(result,columns=['Result'])
  df_result.to_csv("Result_Decision_Tree3.csv", index=None, header=True)

  y_true = df['Cat']
  y_pred = df_result['Result']
  target_names = ['MITM ARP Spoofing','Normal','DoS', 'Mirai','Scan']

  print(classification_report(y_true, y_pred, target_names=target_names))

  cm = confusion_matrix(y_true, y_pred)
  fig, ax = plt.subplots(figsize=(5, 6))
  sns.heatmap(cm, annot=True, fmt=',', cmap='Blues',xticklabels=target_names,yticklabels=target_names, ax=ax)
  ax.set_xlabel('Predicted Label')
  ax.set_ylabel('True Label')
  ax.set_title('Confusion Matrix — Decision Tree IDS')
  plt.tight_layout()
  plt.show()


Decision_Tree_3()

"""## **Step 5 : Build , Train and Evaluation  Random Forest**"""

def Random_Forest():

  df1 = pd.DataFrame(pd.read_csv("Result_Decision_Tree1.csv"))
  df2 = pd.DataFrame(pd.read_csv("Result_Decision_Tree2.csv"))
  df3 = pd.DataFrame(pd.read_csv("Result_Decision_Tree3.csv"))
  df4 = pd.DataFrame(pd.read_csv("IoT Network Intrusion Dataset.csv"))


  df_tree1=df1['Result']
  df_tree2=df2['Result']
  df_tree3=df3['Result']



  conditions=[
            (df_tree1 == df_tree2 ) , (df_tree1 == df_tree3 ),(df_tree2 == df_tree3 ) , (df_tree2 == df_tree1 ),
            (df_tree3 == df_tree1) , (df_tree3 == df_tree2 )
        ]

  Type_attack=[df_tree1,df_tree1, df_tree2,df_tree2,df_tree3,df_tree3]


  result=np.select(conditions,Type_attack,"Normal")
  df_result=pd.DataFrame(result,columns=['Result'])

  y_true = df4['Cat']
  y_pred = df_result['Result']
  target_names = ['MITM ARP Spoofing','Normal','DoS', 'Mirai','Scan']

  print(classification_report(y_true, y_pred, target_names=target_names,digits=4))

  cm = confusion_matrix(y_true, y_pred)
  fig, ax = plt.subplots(figsize=(5, 6))
  sns.heatmap(cm, annot=True, fmt=',', cmap='Blues',xticklabels=target_names,yticklabels=target_names, ax=ax)
  ax.set_xlabel('Predicted Label')
  ax.set_ylabel('True Label')
  ax.set_title('Confusion Matrix — Decision Tree IDS')
  plt.tight_layout()
  plt.show()





Random_Forest()

"""**Normalisation Captured Testing Data**"""

from io import StringIO
from json import loads, dumps

data = pd.DataFrame(pd.read_json("Example.json"))
s=data.to_dict(orient='records')

t=pd.json_normalize(s)
t.to_csv("Result_RDF.csv", index=None, header=True)

print(t)